# Generated by Django 4.2 on 2023-04-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('marital_status', models.CharField(choices=[('ye', 'Женат/Замужем'), ('no', 'Холост/Не замужем')], default='ye', max_length=2, verbose_name='Семейное положение')),
                ('children', models.CharField(default='Нет', max_length=255, verbose_name='Дети')),
                ('registration_address', models.CharField(max_length=300, verbose_name='Адрес регистрации')),
                ('residential_address', models.CharField(max_length=300, verbose_name='Адрес проживания')),
                ('mobile_phone', models.CharField(max_length=11, verbose_name='Мобильный телефон')),
                ('home_phone', models.CharField(default='Нет', max_length=15, verbose_name='Домашний телефон')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('average_perfomance', models.FloatField(blank=True, null=True, verbose_name='Средний балл успеваемости')),
                ('academic_degrees', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ученые степени, звания')),
                ('training_courses', models.CharField(blank=True, max_length=300, null=True, verbose_name='Курсы повышения квалификации')),
                ('professional_skills', models.TextField(blank=True, null=True, verbose_name='Профессиональные навыки')),
                ('software', models.CharField(blank=True, max_length=500, null=True, verbose_name='ПО, которым владеете')),
                ('FIO', models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО рекомендатора')),
                ('work_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место работы рекомендатора')),
                ('position_of_recom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность рекомендатора')),
                ('phone_of_recom', models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон рекомендатора')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('passed_the_questionnaire', models.BooleanField(default='True', verbose_name='Прошел анкету')),
                ('test_result', models.CharField(blank=True, max_length=10, null=True, verbose_name='Результат теста')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Направление')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='DesiredDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=50, verbose_name='Желаемое направление')),
            ],
            options={
                'verbose_name': 'Направления в банке',
                'verbose_name_plural': 'Направления в банке',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.categories', verbose_name='Категории')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Оценка')),
                ('aplicat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.aplication', verbose_name='Клиент')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.test', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='Текст вопроса')),
                ('true_answer', models.CharField(max_length=100, verbose_name='Правильный ответ')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.test', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='HigherEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_university', models.CharField(max_length=150, verbose_name='Название ВУЗа')),
                ('year_of_entry', models.CharField(max_length=4, verbose_name='Год поступления')),
                ('year_of_graduation', models.CharField(max_length=4, verbose_name='Год окончания')),
                ('faculty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Факультет')),
                ('specialization', models.CharField(max_length=100, verbose_name='Специальность')),
                ('form_of_training', models.CharField(choices=[('dn', 'Очная(Дневная)'), ('vc', 'Очная(Вечерняя)'), ('za', 'Заочная')], default='dn', max_length=2, verbose_name='Форма обученя')),
                ('higher_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.aplication')),
            ],
            options={
                'verbose_name': 'Высшее образование',
                'verbose_name_plural': 'Высшее образование',
            },
        ),
        migrations.CreateModel(
            name='ForeignLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('proficiency_level', models.CharField(choices=[('св', 'Свободно'), ('рз', 'Разговорный'), ('чп', 'Читаю/Пишу'), ('чс', 'Читаю/Пишу со словарем')], default='св', max_length=2, verbose_name='Уровень владения')),
                ('foreign_languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.aplication')),
            ],
            options={
                'verbose_name': 'Иностранные языки',
                'verbose_name_plural': 'Иностранные языки',
            },
        ),
        migrations.CreateModel(
            name='FamilyRemember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_in_family', models.CharField(max_length=40, verbose_name='Член семьи')),
                ('FIO', models.CharField(max_length=150, verbose_name='ФИО')),
                ('date_of_birth_fanily', models.DateField(verbose_name='Дата рождения')),
                ('place_of_work', models.CharField(max_length=100, verbose_name='Место работы')),
                ('family_remember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.aplication')),
            ],
            options={
                'verbose_name': 'Члены семьи',
                'verbose_name_plural': 'Члены семьи',
            },
        ),
        migrations.CreateModel(
            name='Enterprises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ent', models.CharField(max_length=100, verbose_name='Название предприятния')),
                ('date_of_dismissal', models.DateField(verbose_name='Дата увольнения')),
                ('post_ent', models.CharField(max_length=100, verbose_name='Должность')),
                ('responsibilities', models.TextField(verbose_name='Обязанности')),
                ('reason_of_leaving', models.CharField(max_length=150, verbose_name='Причина ухода')),
                ('enterprises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.aplication')),
            ],
            options={
                'verbose_name': 'Предприятия',
                'verbose_name_plural': 'Предприятия',
            },
        ),
        migrations.CreateModel(
            name='DirectionOfTheAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('pr', 'Практика'), ('ed', 'Обучение/Стажировка'), ('wk', 'Работа')], default='pr', max_length=100, verbose_name='Цель обращения')),
                ('desired_region', models.CharField(choices=[('РО', 'Ростовская область'), ('КК', 'Краснодарский край'), ('СТ', 'Ставропольский край'), ('ВО', 'Волгоградская область'), ('МО', 'Москва'), ('НН', 'Нижний новгород')], default='РО', max_length=2, verbose_name='Желаемый регион')),
                ('date_with', models.DateField(blank=True, null=True, verbose_name='С')),
                ('date_before', models.DateField(blank=True, null=True, verbose_name='До')),
                ('working_in_bank', models.BooleanField(verbose_name='Хочет работать в банке')),
                ('expectations', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ваши ожидания от работы в Банке')),
                ('removal', models.BooleanField(default=False, verbose_name='Готовность перехать')),
                ('documents_before', models.BooleanField(verbose_name='Подавал ранее')),
                ('results_of_documents', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат подачи')),
                ('desired_direction', models.ManyToManyField(to='aplication.desireddirection', verbose_name='Желаемое направление работы')),
                ('direction_of_the_appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.aplication')),
            ],
            options={
                'verbose_name': 'Направление обращения',
                'verbose_name_plural': 'Направление обращения',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.question', verbose_name='Вопрос')),
            ],
        ),
    ]
